-- Disable RLS for all tables to allow full access for internal tool usage
ALTER TABLE workspaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE social_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE published_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_analytics DISABLE ROW LEVEL SECURITY;
ALTER TABLE account_analytics DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE generated_images DISABLE ROW LEVEL SECURITY;
