export const CAROUSEL_SLIDE_FRAME_CLASS = "w-full min-w-0 overflow-hidden rounded-xl border border-white/10 bg-[#151620]"

export const CAROUSEL_SLIDE_TRACK_CLASS = [
  "flex",
  "flex-col",
  "w-full",
  "min-w-0",
  "gap-3",
  "overflow-x-hidden",
  "px-3",
  "pt-3",
  "pb-3",
  "md:flex-row",
  "md:overflow-x-auto",
  "md:overscroll-x-contain",
  "md:scroll-smooth",
  "md:snap-x",
  "md:snap-mandatory",
  "md:px-4",
  "md:pt-4",
  "md:[-webkit-overflow-scrolling:touch]",
  "md:[touch-action:pan-x]",
  "md:[scrollbar-width:thin]",
].join(" ")

export const CAROUSEL_SLIDE_CARD_CLASS = [
  "flex",
  "h-auto",
  "w-full",
  "max-w-full",
  "min-w-0",
  "shrink",
  "flex-col",
  "gap-2.5",
  "border-white/10",
  "bg-[#1b1d28]",
  "p-3",
  "text-white/85",
  "md:min-h-[320px]",
  "md:gap-3",
  "md:p-4",
  "md:w-[280px]",
  "md:max-w-[320px]",
  "md:shrink-0",
  "md:snap-start",
].join(" ")
