import {
  BarChart3,
  Bot,
  CalendarDays,
  Image as ImageIcon,
  Images,
  Lightbulb,
  MessageSquareText,
  Paintbrush,
  PenLine,
  Settings2,
} from 'lucide-react'
import type { AssistantModeMeta, AssistantQuickStart } from './assistant-types'

export const ASSISTANT_THEME = {
  shell: '#151620',
  shellAlt: '#1b1d28',
  bubble: '#1b1d28',
  border: 'rgba(255,255,255,0.08)',
  borderSoft: 'rgba(255,255,255,0.06)',
  text: 'rgba(255,255,255,0.85)',
  textMuted: 'rgba(255,255,255,0.5)',
  textDim: 'rgba(255,255,255,0.35)',
  cyan: '#38bdf8',
  cyanSoft: '#dff6ff',
  coral: '#fb7185',
  amber: '#fbbf24',
}

export const ASSISTANT_MODES: AssistantModeMeta[] = [
  {
    id: 'create',
    label: 'Create',
    shortLabel: 'Create',
    description: 'Ideas, captions, images, carousels, and drafts.',
    icon: PenLine,
  },
  {
    id: 'improve',
    label: 'Improve',
    shortLabel: 'Improve',
    description: 'Rewrite, shorten, expand, adjust tone, and add CTAs.',
    icon: MessageSquareText,
  },
  {
    id: 'analyze',
    label: 'Analyze',
    shortLabel: 'Analyze',
    description: 'Understand performance, timing, formats, and topics.',
    icon: BarChart3,
  },
  {
    id: 'operate',
    label: 'Operate',
    shortLabel: 'Operate',
    description: 'Inspect posts, schedules, automations, and setup.',
    icon: Settings2,
  },
  {
    id: 'ask',
    label: 'Ask',
    shortLabel: 'Ask',
    description: 'General chat and product help.',
    icon: Bot,
  },
]

export const ASSISTANT_QUICK_STARTS: AssistantQuickStart[] = [
  {
    id: 'create-post',
    mode: 'create',
    action: 'generate_caption',
    title: 'Create post',
    description: 'Draft a post from an idea or topic.',
    prompt: 'Create a social media post about ',
    functionName: 'chat-assistant',
    icon: PenLine,
  },
  {
    id: 'generate-ideas',
    mode: 'create',
    action: 'generate_ideas',
    title: 'Generate ideas',
    description: 'Get content ideas for your brand.',
    prompt: 'Generate content ideas for my brand.',
    functionName: 'generate-ideas',
    icon: Lightbulb,
  },
  {
    id: 'create-image',
    mode: 'create',
    action: 'generate_image',
    title: 'Create image',
    description: 'Generate post-ready visual concepts.',
    prompt: '',
    functionName: 'generate-image',
    icon: ImageIcon,
  },
  {
    id: 'create-carousel',
    mode: 'create',
    action: 'generate_carousel',
    title: 'Create carousel',
    description: 'Build a multi-slide post.',
    prompt: '',
    functionName: 'generate-carousel',
    icon: Images,
  },
  {
    id: 'brand-images',
    mode: 'create',
    action: 'brand_images',
    title: 'Brand images',
    description: 'Generate or transform branded images.',
    prompt: '',
    functionName: 'brand-images',
    icon: Paintbrush,
  },
  {
    id: 'improve-draft',
    mode: 'improve',
    action: 'improve_text',
    title: 'Improve draft',
    description: 'Rewrite a caption or sharpen a hook.',
    prompt: 'Improve this draft: ',
    functionName: 'chat-assistant',
    icon: MessageSquareText,
  },
  {
    id: 'analyze-performance',
    mode: 'analyze',
    action: 'analyze_workspace',
    title: 'Analyze performance',
    description: 'Find what is working and what to post next.',
    prompt: 'Analyze my recent performance and suggest what to post next.',
    functionName: 'chat-assistant',
    icon: BarChart3,
  },
  {
    id: 'plan-week',
    mode: 'create',
    action: 'generate_ideas',
    title: 'Plan week',
    description: 'Create a practical weekly content plan.',
    prompt: 'Plan a week of social media posts for my brand.',
    functionName: 'chat-assistant',
    icon: CalendarDays,
  },
  {
    id: 'manage-automations',
    mode: 'operate',
    action: 'inspect_automations',
    title: 'Manage automations',
    description: 'Review automation setup and next actions.',
    prompt: 'Help me review my active automations.',
    functionName: 'chat-assistant',
    icon: Settings2,
  },
]
